apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o494mr071-go
  janus-idp.io/tekton: o494mr071-go
  backstage.io/kubernetes-id: o494mr071-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o494mr071-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
